apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: ksqldb-cli
  name: ksqldb-cli
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: ksqldb-cli
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: ksqldb-cli
    spec:
      containers:
        - command:
            - /bin/sh
          image: confluentinc/cp-ksqldb-cli:7.7.0
          name: ksqldb-cli
          tty: true
      restartPolicy: Always
